feat: add envoy gateway

diff --git a/deployment/Makefile b/deployment/Makefile
--- a/deployment/Makefile
+++ b/deployment/Makefile
@@ -2,6 +2,7 @@ SHELL:=/bin/bash
 VERSION:=1.0.0
 MODE:=dev
 RUN_ENV:=local
+KEYCLOAK_HOSTNAME:=keycloak.leduynhan1201.dev
 
 dev-auth:
 	docker exec -it -uroot auth-service bash -c 'cd /app && ./gradlew quarkusDev -DdebugHost=0.0.0.0 -DskipTests';
@@ -35,14 +36,24 @@ prepare:
 	@sudo apt-get install -y make openjdk-17-jdk
 	@find scripts/$(RUN_ENV) -type f -name "*.sh" -exec chmod +x {} \;
 
+renew-certs:
+	@if [ -z "$(SERVER_NAME)" ]; then \
+		echo "SERVER_NAME is required. Use: make renew-certs SERVER_NAME=kafka"; \
+		exit 1; \
+	fi
+	@echo "Generating $(SERVER_NAME) certificates..."
+	@./scripts/$(RUN_ENV)/renew_certs.sh $(MODE) $(SERVER_NAME)
+
 .PHONY: init
 init:
 	@echo "Initializing environment..."
 	@./scripts/$(RUN_ENV)/init.sh $(MODE)
+	@sudo cp secrets/certs/ca/ca.crt /usr/local/share/ca-certificates/ldnhanCA.crt
+	@sudo update-ca-certificates
 
 .PHONY: clean
 clean:
-	@echo "Cleaning environment..."
+	@echo "Cleaning all..."
 	@./scripts/$(RUN_ENV)/clean.sh $(MODE)
 
 .PHONY: start
@@ -54,3 +65,6 @@ start:
 stop:
 	@echo "Stopping containers..."
 	@./scripts/$(RUN_ENV)/stop.sh $(MODE)
+
+check-connect:
+	@openssl s_client -connect $(KEYCLOAK_HOSTNAME):443 -servername $(KEYCLOAK_HOSTNAME)
